Next prev but from terminal
willie-shen/ProverbsBox pull request #11
Opened 2020-09-17 01:32 UTC by BC12232

Replacement for the request I just closed. This time I'm correctly merging into development. 
This version has the foward and backward button working for Library.tsx.

2020-09-17 03:18 UTC, matthewfala commented on src/pages/Library.tsx
> +/* QUESTION: How do u know what chapter it's on? Is there a bookmark?
Answered on slack, so not sure if you still want an answer for this. We have ILibraryContext state stored in the library component.

2020-09-17 05:06 UTC, matthewfala requested changes

2020-09-17 05:06 UTC, matthewfala commented on src/pages/Library.tsx
>                          <IonButton fill={"clear"} className="next-button"
If this render function gets long and ugly, you can always extract some components -> the components folder. https://reactjs.org/docs/components-and-props.html#extracting-components

2020-09-17 05:06 UTC, matthewfala commented on src/pages/Library.tsx
> +        this.INCREASE = 0;
can we get rid of this?

2020-09-17 07:10 UTC, BC12232 commented
Ok, changes fixed.

2020-09-18 01:34 UTC, matthewfala approved these changes

2020-09-30 06:20 UTC, merged